### ISSUE TITLE
Add module to access secrets/parameters

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-access-api#13]
# User story
As a user, I want a library to access secrets, so I can import it in other projects.

# Acceptance criteria
- [ ] A user can call a get_secret(secret_name) method that will retrieve a secret if the user has the proper aws permissions
- [ ] A user can call a get_parameter(parameter_name) method that will retrieve a parameter if the user has the proper aws permissions (not as strict as the permissions required for a secret)
- [ ] The dependencies should be self-contained, i.e., the user can run pip install aind-data-access-api[secrets] to just import the external library boto3 essentially.

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
refactor pyproject.toml
