### ISSUE TITLE
Return raw json responses from docdb instead of `DataAssetRecord`

### ISSUE THREAD

**Issue by helen-m-lin** [AllenNeuralDynamics/aind-data-access-api#61]
**Is your feature request related to a problem? Please describe.**
The new metadata_index/data_assets does not adhere to `DataAssetRecord`. Additionally, we want to return the raw response from docdb for the `MetadataDbClient` (API gateway client)

**Describe the solution you'd like**
- Return json response from docdb in `MetadataDbClient`
- Remove `DataAssetRecord` model
- Optional: Add usage examples for API gateway in readthedocs

**Describe alternatives you've considered**

**Additional context**

**Comment by jtyoung84** [comment]
Add new method and deprecate the old one
