### ISSUE TITLE
duplicate data entries when pulling data from mongodb 

### ISSUE THREAD

**Issue by rachelstephlee** [AllenNeuralDynamics/aind-data-access-api#85]
**Describe the bug**
There are duplicate entries when pulling fiber photometry data from mongoDB. There are 629 entries spanning from 2/1/2023 to 6/3/2024. CSV with all duplicated entires attached. 

**To Reproduce**
1. From[ David's capsule](https://codeocean.allenneuraldynamics.org/capsule/9532498/tree), call `df = load_data_from_docDB()`
2. check `df[df.duplicated()]` and you'll see that there are 629 duplicated entries. 
See [duped_entries.csv](https://github.com/user-attachments/files/16681383/duped_entries.csv)

**Expected behavior**
There shouldn't be duplicates data entries. 

**Screenshots**
N/A, see CSV of duplicated entries. 

Found bug on code ocean capsule, running on chrome on a mac, but none of this info should matter.

**Comment by dyf** [comment]
This is an issue with the queries, not the database.  The capsule you linked to issues two queries and combines the results. The responses overlap. I will fix the script.
